services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/progress_tracker
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
    volumes:
      - ./db:/db