# Generated by Django 4.2.6 on 2024-01-06 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_activity_activityitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'name')},
        ),
    ]
